#ifndef SENSORTYPES_H
#define SENSORTYPES_H

typedef enum{
    SENSOR_FUNCTION_NONE,
    SENSOR_FUNCTION_BAT_VOLT,
    SENSOR_FUNCTION_BAT_PERCENT,
    SENSOR_FUNCTION_BAT_MHA,
    SENSOR_FUNCTION_MOTOR_RPM,
    SENSOR_FUNCTION_MOTOR_CURRENT,
    SENSOR_FUNCTION_MOTOR_POWER,
    SENSOR_FUNCTION_MOTOR_TEMP,
    SENSOR_FUNCTION_ESC_TEMP,
    SENSOR_FUNCTION_SPEED,
    SENSOR_FUNCTION_ALTITUDE,
    SENSOR_FUNCTION_XERUN_AXE
} sensorFunction_t;



#endif