#ifndef UNITS_H
#define UNITS_H

typedef enum{
    SENSOR_UNIT_NONE,
    SENSOR_UNIT_VOLTS,
    SENSOR_UNIT_AMPS,
    SENSOR_UNIT_MILLIAMPS,
    SENSOR_UNIT_KNOTS,
    SENSOR_UNIT_METERS_PER_SECOND,
    SENSOR_UNIT_FEET_PER_SECOND,
    SENSOR_UNIT_KMH,
    SENSOR_UNIT_MPH,
    SENSOR_UNIT_METERS,
    SENSOR_UNIT_FEET,
    SENSOR_UNIT_CELSIUS,
    SENSOR_UNIT_FAHRENHEIT,
    SENSOR_UNIT_PERCENT,
    SENSOR_UNIT_MAH,
    SENSOR_UNIT_WATTS,
    SENSOR_UNIT_MILLIWATS,
    SENSOR_UNIT_DB,
    SENSOR_UNIT_RPM,
    SENSOR_UNIT_G,
    SENSOR_UNIT_DEGREE,
    SENSOR_UNIT_RADIANS,
    SENSOR_UNIT_MILLILITERS,
    SENSOR_UNIT_FLOZ,
    SENSOR_UNIT_MILLILITER_PER_MINUTE
} opentxUnits_t;

#endif